// Code generated by protoc-gen-go.
// source: ali_log.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	ali_log.proto
	logs.proto

It has these top-level messages:
	Log
	LogGroup
	LogGroupList
	AsyncServiceLog
	AsyncServiceLogList
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Log struct {
	Time             *uint32        `protobuf:"varint,1,req,name=time" json:"time,omitempty"`
	Contents         []*Log_Content `protobuf:"bytes,2,rep,name=contents" json:"contents,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Log) Reset()                    { *m = Log{} }
func (m *Log) String() string            { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()               {}
func (*Log) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Log) GetTime() uint32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *Log) GetContents() []*Log_Content {
	if m != nil {
		return m.Contents
	}
	return nil
}

type Log_Content struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Log_Content) Reset()                    { *m = Log_Content{} }
func (m *Log_Content) String() string            { return proto.CompactTextString(m) }
func (*Log_Content) ProtoMessage()               {}
func (*Log_Content) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Log_Content) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Log_Content) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type LogGroup struct {
	Logs             []*Log  `protobuf:"bytes,1,rep,name=logs" json:"logs,omitempty"`
	Reserved         *string `protobuf:"bytes,2,opt,name=reserved" json:"reserved,omitempty"`
	Topic            *string `protobuf:"bytes,3,opt,name=topic" json:"topic,omitempty"`
	Source           *string `protobuf:"bytes,4,opt,name=source" json:"source,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LogGroup) Reset()                    { *m = LogGroup{} }
func (m *LogGroup) String() string            { return proto.CompactTextString(m) }
func (*LogGroup) ProtoMessage()               {}
func (*LogGroup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LogGroup) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *LogGroup) GetReserved() string {
	if m != nil && m.Reserved != nil {
		return *m.Reserved
	}
	return ""
}

func (m *LogGroup) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *LogGroup) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

type LogGroupList struct {
	LogGroupList     []*LogGroup `protobuf:"bytes,1,rep,name=logGroupList" json:"logGroupList,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *LogGroupList) Reset()                    { *m = LogGroupList{} }
func (m *LogGroupList) String() string            { return proto.CompactTextString(m) }
func (*LogGroupList) ProtoMessage()               {}
func (*LogGroupList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LogGroupList) GetLogGroupList() []*LogGroup {
	if m != nil {
		return m.LogGroupList
	}
	return nil
}

func init() {
	proto.RegisterType((*Log)(nil), "pb.Log")
	proto.RegisterType((*Log_Content)(nil), "pb.Log.Content")
	proto.RegisterType((*LogGroup)(nil), "pb.LogGroup")
	proto.RegisterType((*LogGroupList)(nil), "pb.LogGroupList")
}

func init() { proto.RegisterFile("ali_log.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0xcc, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0x71, 0x9a, 0x56, 0xb7, 0xce, 0xb6, 0x2a, 0x03, 0x42, 0xf0, 0x54, 0x03, 0xc2, 0x9e,
	0x72, 0xd8, 0x57, 0xf0, 0xe0, 0x25, 0x27, 0xef, 0x22, 0xbb, 0x75, 0x08, 0xc1, 0xb8, 0x13, 0x92,
	0x74, 0xc1, 0xb7, 0x97, 0x4d, 0x23, 0x78, 0x9b, 0xff, 0x07, 0xf3, 0x83, 0xf1, 0xe0, 0xdd, 0x87,
	0x67, 0xab, 0x43, 0xe4, 0xcc, 0x28, 0xc2, 0x51, 0xbd, 0x43, 0x6b, 0xd8, 0xe2, 0x00, 0x5d, 0x76,
	0xdf, 0x24, 0x9b, 0x49, 0xec, 0x46, 0x7c, 0x82, 0x7e, 0xe6, 0x53, 0xa6, 0x53, 0x4e, 0x52, 0x4c,
	0xed, 0x6e, 0xbb, 0xbf, 0xd3, 0xe1, 0xa8, 0x0d, 0x5b, 0xfd, 0xb2, 0xee, 0x8f, 0xcf, 0xb0, 0xa9,
	0x27, 0x6e, 0xa1, 0xfd, 0xa2, 0x9f, 0xf2, 0x7a, 0x83, 0x23, 0x5c, 0x9d, 0x0f, 0x7e, 0x21, 0x29,
	0x2e, 0xa9, 0xde, 0xa0, 0x37, 0x6c, 0x5f, 0x23, 0x2f, 0x01, 0x1f, 0xa0, 0xf3, 0x6c, 0x93, 0x6c,
	0x8a, 0xb8, 0xa9, 0x22, 0xde, 0x43, 0x1f, 0x29, 0x51, 0x3c, 0xd3, 0xa7, 0x14, 0x53, 0xb3, 0x1a,
	0x99, 0x83, 0x9b, 0x65, 0x5b, 0xf2, 0x16, 0xae, 0x13, 0x2f, 0x71, 0x26, 0xd9, 0x5d, 0x5a, 0xed,
	0x61, 0xf8, 0x33, 0x8d, 0x4b, 0x19, 0x15, 0x0c, 0xfe, 0x5f, 0x57, 0x7f, 0xa8, 0x7e, 0xd9, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xcd, 0x31, 0xb3, 0xfa, 0x00, 0x00, 0x00,
}
